version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-sqs
    ports:
      - "4566:4566"  # LocalStack main port
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - HOSTNAME_EXTERNAL=localhost
      - DATA_DIR=/var/lib/localstack/data
    volumes:
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  mongodb:
    image: mongo:7
    container_name: mongodb-masterworkers
    ports:
      - "27017:27017"  # MongoDB default port
    environment:
      - MONGO_INITDB_DATABASE=masterworkers
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    command: mongod --bind_ip_all

volumes:
  mongodb_data:
    driver: local
  localstack_data:
    driver: local

networks:
  default:
    name: masterworkers-network
